program PCP4;

{%File 'include\definiciones.inc'}

uses
  _MDI in '_MDI.pas' {_fMDI},
  Forms,
  sysUtils,
  Windows,
  n1_para_plantas in 'n1_para_plantas.pas' {fn1_para_plantas},
  _func_pcp in '_func_pcp.pas',
  _func_varias in '_func_varias.pas',
  _vent_child in '_vent_child.pas' {_fvent_child},
  _vent_modal in '_vent_modal.pas' {_fvent_modal},
  n1_para_empresas in 'n1_para_empresas.pas' {FN1_Para_Empresas},
  UN1_Para_Paises in 'UN1_Para_Paises.pas' {FN1_Para_Paises},
  UN1_Para_Paises1 in 'UN1_Para_Paises1.pas' {FN1_Para_Paises1},
  _vari_pcp in '_vari_pcp.pas',
  UN1_Para_Departamentos in 'UN1_Para_Departamentos.pas' {FN1_Para_Departamentos},
  UN1_Para_Departamentos1 in 'UN1_Para_Departamentos1.pas' {FN1_Para_Departamentos1},
  un1_refe_marcas in 'un1_refe_marcas.pas' {fn1_refe_marcas},
  un1_refe_marcas1 in 'un1_refe_marcas1.pas' {fn1_refe_marcas1},
  UN1_Para_Municipios in 'UN1_Para_Municipios.pas' {FN1_Para_Municipios},
  UN1_Para_Municipios1 in 'UN1_Para_Municipios1.pas' {FN1_Para_Municipios1},
  _Informes in '_Informes.pas' {FInformes},
  UN1_Para_Empresas1 in 'UN1_Para_Empresas1.pas' {FN1_Para_Empresas1},
  ufra_fotografiaDB in 'ufra_fotografiaDB.pas' {ffra_fotografiaDB: TFrame},
  un1_refe_bordados in 'un1_refe_bordados.pas' {fn1_refe_bordados},
  UN1_Para_Areas in 'UN1_Para_Areas.pas' {FN1_Para_Areas},
  UN1_Para_Areas1 in 'UN1_Para_Areas1.pas' {FN1_Para_Areas1},
  UN1_para_plantas1 in 'UN1_para_plantas1.pas' {fn1_para_plantas1},
  UN1_Para_Secciones in 'UN1_Para_Secciones.pas' {FN1_Para_Secciones},
  UN1_Para_Secciones1 in 'UN1_Para_Secciones1.pas' {FN1_Para_Secciones1},
  UN1_Para_Bodegas in 'UN1_Para_Bodegas.pas' {FN1_Para_Bodegas},
  UN1_Para_Bodegas1 in 'UN1_Para_Bodegas1.pas' {FN1_Para_Bodegas1},
  un1_referencias in 'un1_referencias.pas' {fn1_referencias},
  UN1_Para_Turnos in 'UN1_Para_Turnos.pas' {FN1_Para_Turnos},
  UN1_Para_Turnos1 in 'UN1_Para_Turnos1.pas' {FN1_Para_Turnos1},
  UN1_Para_Cargos in 'UN1_Para_Cargos.pas' {FN1_Para_Cargos},
  UN1_Para_Cent_Costos in 'UN1_Para_Cent_Costos.pas' {FN1_Para_Cent_Costos},
  UN1_Para_Cent_Costos1 in 'UN1_Para_Cent_Costos1.pas' {FN1_Para_Cent_Costos1},
  UN1_Para_Cargos1 in 'UN1_Para_Cargos1.pas' {FN1_Para_Cargos1},
  UN1_Pers_Personal in 'UN1_Pers_Personal.pas' {FN1_Pers_Personal},
  UN1_Pers_General1 in 'UN1_Pers_General1.pas' {FN1_Pers_General1},
  UN1_Para_Tipo_Contrato in 'UN1_Para_Tipo_Contrato.pas' {FN1_Para_Tipo_Contrato},
  UN1_Para_Tipo_Contrato1 in 'UN1_Para_Tipo_Contrato1.pas' {FN1_Para_Tipo_Contrato1},
  UN1_Para_Nive_Salariales in 'UN1_Para_Nive_Salariales.pas' {FN1_Para_Nive_Salariales},
  UN1_Para_Nive_Salariales1 in 'UN1_Para_Nive_Salariales1.pas' {FN1_Para_Nive_Salariales1},
  ufra_historialdb in 'ufra_historialdb.pas' {ffra_historialDB: TFrame},
  n0_anotacion in 'n0_anotacion.pas' {fn0_anotacion},
  UN1_Para_Parentescos in 'UN1_Para_Parentescos.pas' {FN1_Para_Parentescos},
  UN1_Para_Parentescos1 in 'UN1_Para_Parentescos1.pas' {FN1_Para_Parentescos1},
  UN1_Para_Tipo_Documento in 'UN1_Para_Tipo_Documento.pas' {FN1_Para_Tipo_Documento},
  UN1_Para_Tipo_Documento1 in 'UN1_Para_Tipo_Documento1.pas' {FN1_Para_Tipo_Documento1},
  un1_refe_bordados1 in 'un1_refe_bordados1.pas' {fn1_refe_bordados1},
  un1_refe_colores in 'un1_refe_colores.pas' {fn1_refe_colores},
  un1_refe_colores1 in 'un1_refe_colores1.pas' {fn1_refe_colores1},
  un1_refe_edades in 'un1_refe_edades.pas' {fn1_refe_edades},
  un1_refe_edades1 in 'un1_refe_edades1.pas' {fn1_refe_edades1},
  un1_refe_estados in 'un1_refe_estados.pas' {fn1_refe_estados},
  un1_refe_estados1 in 'un1_refe_estados1.pas' {fn1_refe_estados1},
  un1_refe_estampados in 'un1_refe_estampados.pas' {fn1_refe_estampados},
  un1_refe_estampados1 in 'un1_refe_estampados1.pas' {fn1_refe_estampados1},
  un1_refe_estilos in 'un1_refe_estilos.pas' {fn1_refe_estilos},
  un1_refe_estilos1 in 'un1_refe_estilos1.pas' {fn1_refe_estilos1},
  Un1_refe_grup_tallas1 in 'Un1_refe_grup_tallas1.pas' {fn1_refe_grup_tallas1},
  un1_refe_grup_tallas in 'un1_refe_grup_tallas.pas' {fn1_refe_grup_tallas},
  un1_refe_grupos in 'un1_refe_grupos.pas' {fn1_refe_grupos},
  un1_refe_grupos1 in 'un1_refe_grupos1.pas' {fn1_refe_grupos1},
  un1_refe_lavados in 'un1_refe_lavados.pas' {fn1_refe_lavados},
  un1_refe_lavados1 in 'un1_refe_lavados1.pas' {fn1_refe_lavados1},
  un1_refe_lineas in 'un1_refe_lineas.pas' {fn1_refe_lineas},
  un1_refe_lineas1 in 'un1_refe_lineas1.pas' {fn1_refe_lineas1},
  un1_refe_temporadas in 'un1_refe_temporadas.pas' {fn1_refe_temporadas},
  un1_refe_temporadas1 in 'un1_refe_temporadas1.pas' {fn1_refe_temporadas1},
  _InputForm in '_InputForm.pas' {_fInputForm},
  ufra_mens_atencion in 'ufra_mens_atencion.pas' {ffra_mens_atencion: TFrame},
  un1_maqu_familias in 'un1_maqu_familias.pas' {fn1_maqu_familias},
  un1_maqu_familias1 in 'un1_maqu_familias1.pas' {fn1_maqu_familias1},
  un1_maqu_grupos in 'un1_maqu_grupos.pas' {fn1_maqu_grupos},
  un1_maqu_grupos1 in 'un1_maqu_grupos1.pas' {fn1_maqu_grupos1},
  un1_maqu_ingreso in 'un1_maqu_ingreso.pas' {fn1_maqu_ingreso},
  un1_maqu_ingreso1 in 'un1_maqu_ingreso1.pas' {fn1_maqu_ingreso1},
  un1_maqu_marcas in 'un1_maqu_marcas.pas' {fn1_maqu_marcas},
  un1_maqu_marcas1 in 'un1_maqu_marcas1.pas' {fn1_maqu_marcas1},
  un1_maqu_tipo_movimiento in 'un1_maqu_tipo_movimiento.pas' {fn1_maqu_tipo_movimiento},
  un1_maqu_tipo_movimiento1 in 'un1_maqu_tipo_movimiento1.pas' {fn1_maqu_tipo_movimiento1},
  un1_maqu_tipo_puntada in 'un1_maqu_tipo_puntada.pas' {fn1_maqu_tipo_puntada},
  un1_maqu_tipo_puntada1 in 'un1_maqu_tipo_puntada1.pas' {fn1_maqu_tipo_puntada1},
  un1_maqu_tipos in 'un1_maqu_tipos.pas' {fn1_maqu_tipos},
  un1_maqu_tipos1 in 'un1_maqu_tipos1.pas' {fn1_maqu_tipos1},
  UN1_Para_Improductivos in 'UN1_Para_Improductivos.pas' {FN1_Para_Improductivos},
  UN1_Para_Improductivos1 in 'UN1_Para_Improductivos1.pas' {FN1_Para_Improductivos1},
  ufra_maqu_ubicacion in 'ufra_maqu_ubicacion.pas' {ffra_maqu_ubicacion: TFrame},
  un1_maqu_traslados in 'un1_maqu_traslados.pas' {fn1_maqu_traslados},
  Un1_maqu_generales1 in 'Un1_maqu_generales1.pas' {fn1_maqu_generales1},
  UN1_Para_Sub_Improductivos in 'UN1_Para_Sub_Improductivos.pas' {FN1_Para_Sub_Improductivos},
  UN1_Para_Sub_Improductivos1 in 'UN1_Para_Sub_Improductivos1.pas' {FN1_Para_Sub_Improductivos1},
  ufra_ubic_regional in 'ufra_ubic_regional.pas' {ffra_ubic_regional: TFrame},
  ufra_empresa in 'ufra_empresa.pas' {ffra_empresa: TFrame},
  UN1_Para_Lineas in 'UN1_Para_Lineas.pas' {FN1_Para_Lineas},
  UN1_Para_Lineas1 in 'UN1_Para_Lineas1.pas' {FN1_Para_Lineas1},
  UN1_Pers_Ingreso in 'UN1_Pers_Ingreso.pas' {FN1_Pers_Ingreso},
  UN1_Pers_Ingreso1 in 'UN1_Pers_Ingreso1.pas' {FN1_Pers_Ingreso1},
  UN1_Para_Colo_Grupos in 'UN1_Para_Colo_Grupos.pas' {FN1_Para_Colo_Grupos},
  UN1_Para_Colo_Grupos1 in 'UN1_Para_Colo_Grupos1.pas' {FN1_Para_Colo_Grupos1},
  Un1_Para_Colo_Sub_Grupos in 'Un1_Para_Colo_Sub_Grupos.pas' {Fn1_Para_Colo_Sub_Grupos},
  Un1_Para_Colo_Sub_Grupos1 in 'Un1_Para_Colo_Sub_Grupos1.pas' {Fn1_Para_Colo_Sub_Grupos1},
  UN1_Para_Colo_Tonos in 'UN1_Para_Colo_Tonos.pas' {FN1_Para_Colo_Tonos},
  UN1_Para_Colo_Tonos1 in 'UN1_Para_Colo_Tonos1.pas' {FN1_Para_Colo_Tonos1},
  UN1_Pers_Reingresos1 in 'UN1_Pers_Reingresos1.pas' {FN1_Pers_Reingresos1},
  un1_maqu_traslados1 in 'un1_maqu_traslados1.pas' {fn1_maqu_traslados1},
  UN1_Para_Tipo_Caracteristicas in 'UN1_Para_Tipo_Caracteristicas.pas' {FN1_Para_Tipo_Caracteristicas},
  UN1_Para_Tipo_Caracteristicas1 in 'UN1_Para_Tipo_Caracteristicas1.pas' {FN1_Para_Tipo_Caracteristicas1},
  UN1_Pers_Movi_Tipo_Documento in 'UN1_Pers_Movi_Tipo_Documento.pas' {FN1_Pers_Movi_Tipo_Documento},
  UN1_Pers_Movi_Tipo_Documento1 in 'UN1_Pers_Movi_Tipo_Documento1.pas' {FN1_Pers_Movi_Tipo_Documento1},
  _vent_modal_alone in '_vent_modal_alone.pas' {_fvent_modal_alone},
  un1_maqu_bajas1 in 'un1_maqu_bajas1.pas' {fn1_maqu_bajas1},
  un1_maqu_reingresos1 in 'un1_maqu_reingresos1.pas' {fn1_maqu_reingresos1},
  UN1_Pers_Maes_Anulados in 'UN1_Pers_Maes_Anulados.pas' {FN1_Pers_Maes_Anulados},
  UN1_Para_Plan_Lineas1 in 'UN1_Para_Plan_Lineas1.pas' {FN1_Para_Plan_Lineas1},
  UN1_Para_Line_Secciones1 in 'UN1_Para_Line_Secciones1.pas' {FN1_Para_Line_Secciones1},
  UN1_Pers_Prestaciones1 in 'UN1_Pers_Prestaciones1.pas' {FN1_Pers_Prestaciones1},
  ufra_sele_referencia in 'ufra_sele_referencia.pas' {ffra_sele_referencia: TFrame},
  _Vent_Most_Imagen in '_Vent_Most_Imagen.pas' {_FVent_Most_Imagen},
  UN1_Acce_Grupos in 'UN1_Acce_Grupos.pas' {FN1_Acce_Grupos},
  UN1_Acce_Grupos1 in 'UN1_Acce_Grupos1.pas' {FN1_Acce_Grupos1},
  UN1_Acce_Tipos in 'UN1_Acce_Tipos.pas' {FN1_Acce_Tipos},
  UN1_Acce_Tipos1 in 'UN1_Acce_Tipos1.pas' {FN1_Acce_Tipos1},
  UN1_Maqu_Fami_tipo_caracteristica1 in 'UN1_Maqu_Fami_tipo_caracteristica1.pas' {FN1_Maqu_Fami_tipo_caracteristica1},
  UN1_Acce_Tipo_Tipo_Caracteristica1 in 'UN1_Acce_Tipo_Tipo_Caracteristica1.pas' {FN1_Acce_Tipo_Tipo_Caracteristica1},
  UN1_Acce_Caracteristicas in 'UN1_Acce_Caracteristicas.pas' {FN1_Acce_Caracteristicas},
  UN1_Acce_Caracteristicas1 in 'UN1_Acce_Caracteristicas1.pas' {FN1_Acce_Caracteristicas1},
  UN1_Acce_Ingreso in 'UN1_Acce_Ingreso.pas' {FN1_Acce_Ingreso},
  UN1_Acce_Ingreso1 in 'UN1_Acce_Ingreso1.pas' {FN1_Acce_Ingreso1},
  UN1_Pers_Familiares1 in 'UN1_Pers_Familiares1.pas' {FN1_Pers_Familiares1},
  UFra_Contactos in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Frames\UFra_Contactos.pas' {FFra_Contactos: TFrame},
  Upara_terceros1 in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Terceros\Upara_terceros1.pas' {fpara_terceros1},
  Upara_terceros in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Terceros\Upara_terceros.pas' {fpara_terceros},
  _UContactos in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Frames\_UContactos.pas' {_fcontactos},
  Upara_facturar1 in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Terceros\Upara_facturar1.pas' {Fpara_facturar1},
  Upara_despachar1 in '..\..\PCP\SourcePCP4_2005_11_28\pct1\Source\Terceros\Upara_despachar1.pas' {Fpara_despachar1},
  un2_come_zonas2 in 'un2_come_zonas2.pas' {fn2_come_zonas2},
  un2_come_pedidos in 'un2_come_pedidos.pas' {fn2_come_pedidos},
  un2_come_prio_pedidos in 'un2_come_prio_pedidos.pas' {fn2_come_prio_pedidos},
  un2_come_prio_pedidos1 in 'un2_come_prio_pedidos1.pas' {fn2_come_prio_pedidos1},
  un2_come_vendedores in 'un2_come_vendedores.pas' {fn2_come_vendedores},
  un2_come_vendedores2 in 'un2_come_vendedores2.pas' {fn2_come_vendedores2},
  un2_come_zonas in 'un2_come_zonas.pas' {fn2_come_zonas},
  un2_come_zonas_detalle in 'un2_come_zonas_detalle.pas' {fn2_come_zonas_detalle},
  un2_come_clientes in 'un2_come_clientes.pas' {fn2_come_clientes},
  UN1_Acce_Traslados1 in 'UN1_Acce_Traslados1.pas' {FN1_Acce_Traslados1},
  UN1_Acce_General1 in 'UN1_Acce_General1.pas' {FN1_Acce_General1},
  UN1_Acce_Bajas1 in 'UN1_Acce_Bajas1.pas' {FN1_Acce_Bajas1},
  UN1_Acce_Reingresos1 in 'UN1_Acce_Reingresos1.pas' {FN1_Acce_Reingresos1},
  UN1_Maqu_Maes_Anulados in 'UN1_Maqu_Maes_Anulados.pas' {FN1_Maqu_Maes_Anulados},
  UN1_Acce_Maes_Anulados in 'UN1_Acce_Maes_Anulados.pas' {FN1_Acce_Maes_Anulados},
  UCN1_Pers_General in 'UCN1_Pers_General.pas' {CN1_Pers_General},
  UN1_Para_Firmas in 'UN1_Para_Firmas.pas' {FN1_Para_Firmas},
  UN1_Para_Firmas1 in 'UN1_Para_Firmas1.pas' {FN1_Para_Firmas1},
  UN1_Para_Prioridades in 'UN1_Para_Prioridades.pas' {FN1_Para_Prioridades},
  UN1_Para_Prioridades1 in 'UN1_Para_Prioridades1.pas' {FN1_Para_Prioridades1},
  un2_come_pedi_consultas in 'un2_come_pedi_consultas.pas' {fn2_come_pedi_consultas},
  un2_come_pedi_planeacion in 'un2_come_pedi_planeacion.pas' {fn2_come_pedi_planeacion},
  UN1_para_informes in 'UN1_para_informes.pas' {FN1_para_informes},
  Un1_Pers_Tipo_Movimientos in 'Un1_Pers_Tipo_Movimientos.pas' {Fn1_Pers_Tipo_Movimientos},
  Un1_Pers_Tipo_Movimientos1 in 'Un1_Pers_Tipo_Movimientos1.pas' {Fn1_Pers_Tipo_Movimientos1},
  UCN1_Pers_Historial in 'UCN1_Pers_Historial.pas' {CN1_Pers_Historial},
  URN1_Pers_Historial in 'URN1_Pers_Historial.pas' {RN1_Pers_Historial},
  UCN1_Maqu_General in 'UCN1_Maqu_General.pas' {CN1_Maqu_General},
  UCN1_Maqu_Traslados in 'UCN1_Maqu_Traslados.pas' {CN1_Maqu_Traslados},
  URN1_Maqu_Traslados in 'URN1_Maqu_Traslados.pas' {RN1_Maqu_Traslados},
  UCN1_Maqu_Cons_Plantas in 'UCN1_Maqu_Cons_Plantas.pas' {CN1_Maqu_Cons_Plantas},
  URN1_Maqu_Cons_Plantas in 'URN1_Maqu_Cons_Plantas.pas' {RN1_Maqu_Cons_Plantas},
  ufra_prod_orde_unidades in 'ufra_prod_orde_unidades.pas' {ffra_prod_orde_unidades: TFrame},
  ufra_list_referencias in 'ufra_list_referencias.pas' {ffra_list_referencias: TFrame},
  ufra_prod_expl_insumos in 'ufra_prod_expl_insumos.pas' {ffra_prod_expl_insumos: TFrame},
  ufra_prod_expl_tejidos in 'ufra_prod_expl_tejidos.pas' {ffra_prod_expl_tejidos: TFrame},
  ufra_prod_orde_etapas in 'ufra_prod_orde_etapas.pas' {ffra_prod_orde_etapas: TFrame},
  ufra_prod_orde_pedidos in 'ufra_prod_orde_pedidos.pas' {ffra_prod_orde_pedidos: TFrame},
  ufra_refe_material in 'ufra_refe_material.pas' {ffra_refe_material: TFrame},
  ufra_prod_orde_loteo in 'ufra_prod_orde_loteo.pas' {ffra_prod_orde_loteo: TFrame},
  un1_prod_depe_etapas in 'un1_prod_depe_etapas.pas' {fn1_prod_depe_etapas},
  Un1_Maqu_Dato_Fich_Tecnica in 'Un1_Maqu_Dato_Fich_Tecnica.pas' {Fn1_Maqu_Dato_Fich_Tecnica},
  URn1_Maqu_Dato_Fich_Tecnica in 'URn1_Maqu_Dato_Fich_Tecnica.pas' {Rn1_Maqu_Dato_Fich_Tecnica},
  UCN1_Acce_General in 'UCN1_Acce_General.pas' {CN1_Acce_General},
  UCN1_Acce_Traslados in 'UCN1_Acce_Traslados.pas' {CN1_Acce_Traslados},
  URN1_Acce_Traslados in 'URN1_Acce_Traslados.pas' {RN1_Acce_Traslados},
  UCN1_Acce_Cons_Plantas in 'UCN1_Acce_Cons_Plantas.pas' {CN1_Acce_Cons_Plantas},
  URN1_Acce_Cons_Plantas in 'URN1_Acce_Cons_Plantas.pas' {RN1_Acce_Cons_Plantas},
  ufra_prod_sele_lote in 'ufra_prod_sele_lote.pas' {ffra_prod_sele_lote: TFrame},
  ufra_prod_resp_lote_proceso in 'ufra_prod_resp_lote_proceso.pas' {ffra_prod_resp_lote_proceso: TFrame},
  ufra_prod_tiqu_corte in 'ufra_prod_tiqu_corte.pas' {ffra_prod_tiqu_corte: TFrame},
  UN1_Refe_Pres_Empaque1 in 'UN1_Refe_Pres_Empaque1.pas' {FN1_Refe_Pres_Empaque1},
  ufra_prod_maestro in 'ufra_prod_maestro.pas' {ffra_prod_maestro: TFrame},
  ufra_prod_orde_unid_lote in 'ufra_prod_orde_unid_lote.pas' {ffra_prod_orde_unid_lote: TFrame},
  ufra_prod_orde_dist_paquetes in 'ufra_prod_orde_dist_paquetes.pas' {ffra_prod_orde_dist_paquetes: TFrame},
  ufra_dependencias in 'ufra_dependencias.pas' {ffra_dependencias: TFrame},
  un1_refe_entrepiernas in 'un1_refe_entrepiernas.pas' {fn1_refe_entrepiernas},
  un1_refe_entrepiernas1 in 'un1_refe_entrepiernas1.pas' {fn1_refe_entrepiernas1},
  un2_come_clientes1 in 'un2_come_clientes1.pas' {fn2_come_clientes1},
  ufra_sele_refe_variacion in 'ufra_sele_refe_variacion.pas' {ffra_sele_refe_variacion: TFrame},
  ufra_sele_color in 'ufra_sele_color.pas' {ffra_sele_color: TFrame},
  urn1_refe_list_materiales in 'urn1_refe_list_materiales.pas' {Rn1_refe_list_materiales},
  urn1_refe_list_mate_colores in 'urn1_refe_list_mate_colores.pas' {Rn1_refe_list_mate_colores},
  un1_refe_asig_materiales in 'un1_refe_asig_materiales.pas' {fn1_refe_asig_materiales},
  un1_refe_asig_insumos in 'un1_refe_asig_insumos.pas' {fn1_refe_asig_insumos},
  un1_refe_camb_estado in 'un1_refe_camb_estado.pas' {fn1_refe_camb_estado},
  un1_para_monedas in 'un1_para_monedas.pas' {fn1_para_monedas},
  un1_para_monedas1 in 'un1_para_monedas1.pas' {fn1_para_monedas1},
  un1_para_mone_trm in 'un1_para_mone_trm.pas' {fn1_para_mone_trm},
  un1_para_mone_trm1 in 'un1_para_mone_trm1.pas' {fn1_para_mone_trm1},
  ufra_sele_componentes in 'ufra_sele_componentes.pas' {ffra_sele_componentes: TFrame},
  un1_meto_refe_list_operaciones in 'un1_meto_refe_list_operaciones.pas' {fn1_meto_refe_list_operaciones},
  un2_prototipos in 'un2_prototipos.pas' {fn2_prototipos},
  un2_prototipos1 in 'un2_prototipos1.pas' {fn2_prototipos1},
  un1_refe_list_materiales in 'un1_refe_list_materiales.pas' {fn1_refe_list_materiales},
  un2_prot_list_materiales in 'un2_prot_list_materiales.pas' {fn2_prot_list_materiales},
  un2_prot_list_oper_costura in 'un2_prot_list_oper_costura.pas' {fn2_prot_list_oper_costura},
  urn1_meto_list_operaciones in 'urn1_meto_list_operaciones.pas' {rn1_meto_list_operaciones},
  un1_meto_refe_list_oper_corte in 'un1_meto_refe_list_oper_corte.pas' {fn1_meto_refe_list_oper_corte},
  un1_refe_list_mate_copiar in 'un1_refe_list_mate_copiar.pas' {fn1_refe_list_mate_copiar},
  un2_prot_list_mate_copiar in 'un2_prot_list_mate_copiar.pas' {fn2_prot_list_mate_copiar},
  un2_prot_camb_estado in 'un2_prot_camb_estado.pas' {fn2_prot_camb_estado},
  urn1_refe_base_informe in 'urn1_refe_base_informe.pas' {rn1_refe_base_informe},
  urn1_meto_list_oper_corte in 'urn1_meto_list_oper_corte.pas' {rn1_meto_list_oper_corte},
  un0_usua_permisos in 'un0_usua_permisos.pas' {fn0_usua_permisos},
  un0_usua_mantenimiento in 'un0_usua_mantenimiento.pas' {fn0_usua_mantenimiento},
  un0_usua_mantenimiento1 in 'un0_usua_mantenimiento1.pas' {fn0_usua_mantenimiento1},
  un0_acce_directos in 'un0_acce_directos.pas' {fn0_acce_directos},
  un1_meto_procesos1 in 'un1_meto_procesos1.pas' {fn1_meto_procesos1},
  un1_meto_procesos in 'un1_meto_procesos.pas' {fn1_meto_procesos},
  un2_come_cotizaciones in 'un2_come_cotizaciones.pas' {fn2_come_cotizaciones},
  un2_come_comp_envio in 'un2_come_comp_envio.pas' {fn2_come_comp_envio},
  un2_come_comp_envio1 in 'un2_come_comp_envio1.pas' {fn2_come_comp_envio1},
  un1_meto_list_oper_cort_detalle in 'un1_meto_list_oper_cort_detalle.pas' {fn1_meto_list_oper_cort_detalle},
  urn1_meto_list_oper_cost_detalle in 'urn1_meto_list_oper_cost_detalle.pas' {rn1_meto_list_oper_cost_detalle},
  un2_come_pedidos1 in 'un2_come_pedidos1.pas' {fn2_come_pedidos1},
  un1_meto_estandar1 in 'un1_meto_estandar1.pas' {fn1_meto_estandar1},
  un1_meto_elem_cst in 'un1_meto_elem_cst.pas' {fn1_meto_elem_cst},
  un1_meto_elem_cst1 in 'un1_meto_elem_cst1.pas' {fn1_meto_elem_cst1},
  un1_meto_estandar in 'un1_meto_estandar.pas' {fn1_meto_estandar},
  un1_plan_cale_produccion in 'un1_plan_cale_produccion.pas' {fn1_plan_cale_produccion},
  ufra_sele_empr_plan_line_seccion in 'ufra_sele_empr_plan_line_seccion.pas' {ffra_sele_empr_plan_line_seccion: TFrame},
  un0_usua_camb_contrasena in 'un0_usua_camb_contrasena.pas' {fn0_usua_camb_contrasena},
  un0_opciones in 'un0_opciones.pas' {fn0_opciones},
  un0_usua_bloq_sesion in 'un0_usua_bloq_sesion.pas' {fn0_usua_bloq_sesion},
  un2_come_pedi_cons_general in 'un2_come_pedi_cons_general.pas' {fn2_come_pedi_cons_general},
  un2_come_pedi_explosion in 'un2_come_pedi_explosion.pas' {fn2_come_pedi_explosion},
  un2_come_pedi_cons_por_cliente in 'un2_come_pedi_cons_por_cliente.pas' {fn2_come_pedi_cons_por_cliente},
  un1_inge_punt_control in 'un1_inge_punt_control.pas' {fn1_inge_punt_control},
  un1_inge_punt_control1 in 'un1_inge_punt_control1.pas' {fn1_inge_punt_control1},
  un1_prod_paqu_tipos1 in 'un1_prod_paqu_tipos1.pas' {fn1_prod_paqu_tipos1},
  urn1_meto_elem_cst in 'urn1_meto_elem_cst.pas' {rn1_meto_elem_cst},
  un1_meto_cst_tiem_maquina in 'un1_meto_cst_tiem_maquina.pas' {fn1_meto_cst_tiem_maquina},
  urn1_meto_oper_cst_general in 'urn1_meto_oper_cst_general.pas' {rn1_meto_oper_cst_general},
  urn1_meto_oper_cst_info_operacion in 'urn1_meto_oper_cst_info_operacion.pas' {rn1_meto_oper_cst_info_operacion},
  urn1_meto_oper_cst_list_elementos in 'urn1_meto_oper_cst_list_elementos.pas' {rn1_meto_oper_cst_list_elementos},
  urn1_meto_oper_cst_puest_trabjo in 'urn1_meto_oper_cst_puest_trabjo.pas' {rn1_meto_oper_cst_puest_trabjo},
  un1_prod_padre in 'un1_prod_padre.pas' {fn1_prod_padre},
  un1_prod_loteo in 'un1_prod_loteo.pas' {fn1_prod_loteo},
  ufra_prod_sele_espiga in 'ufra_prod_sele_espiga.pas' {ffra_prod_sele_espiga: TFrame},
  ufra_prod_orde_trazo in 'ufra_prod_orde_trazo.pas' {ffra_prod_orde_trazo: TFrame},
  un1_prod_orde_traz_total in 'un1_prod_orde_traz_total.pas' {fn1_prod_orde_traz_total},
  un1_prod_plan_detallada in 'un1_prod_plan_detallada.pas' {fn1_prod_plan_detallada},
  un1_para_estructura in 'un1_para_estructura.pas' {fn1_para_estructura},
  un1_para_plan_line_adicionar in 'un1_para_plan_line_adicionar.pas' {fn1_para_plan_line_adicionar},
  UN1_Para_line_secciones_adicionar in 'UN1_Para_line_secciones_adicionar.pas' {fN1_Para_line_secciones_adicionar},
  un1_prod_oper_corte in 'un1_prod_oper_corte.pas' {fn1_prod_oper_corte},
  uWizard in 'uWizard.pas' {fWizard},
  ufra_ordenar in 'ufra_ordenar.pas' {ffra_ordenar: TFrame},
  uwn1_prod_cort_impr_tiquetes in 'uwn1_prod_cort_impr_tiquetes.pas' {fwn1_prod_cort_impr_tiquetes},
  un1_prod_estado in 'un1_prod_estado.pas' {fn1_prod_estado},
  un1_prod_esta_editar in 'un1_prod_esta_editar.pas' {fn1_prod_esta_editar},
  un1_cont_abonados1 in 'un1_cont_abonados1.pas' {fn1_cont_abonados1},
  un1_cont_abonados in 'un1_cont_abonados.pas' {fn1_cont_abonados},
  un1_cont_hora_extras in 'un1_cont_hora_extras.pas' {fn1_cont_hora_extras},
  un1_cont_hora_extras1 in 'un1_cont_hora_extras1.pas' {fn1_cont_hora_extras1},
  un1_pers_bajas in 'un1_pers_bajas.pas' {fn1_pers_bajas},
  un1_pers_traslados2 in 'un1_pers_traslados2.pas' {fn1_pers_traslados2},
  ucn1_pers_ubicacion in 'ucn1_pers_ubicacion.pas' {cn1_pers_ubicacion},
  ufra_sele_pers_lista in 'ufra_sele_pers_lista.pas' {ffra_sele_pers_lista: TFrame},
  un1_pers_dato_confidenciales in 'un1_pers_dato_confidenciales.pas' {fn1_pers_dato_confidenciales},
  ufra_prod_list_oper_costura in 'UFRA_PROD_LIST_OPER_COSTURA.pas' {ffra_prod_list_oper_costura: TFrame},
  un1_prod_oper_costura in 'un1_prod_oper_costura.pas' {fn1_prod_oper_costura},
  ucn1_prod_cons_gene_fechas in 'ucn1_prod_cons_gene_fechas.pas' {cn1_prod_cons_gene_fechas},
  ucn1_prod_cons_gene_unidad in 'ucn1_prod_cons_gene_unidad.pas' {cn1_prod_cons_gene_unidad},
  ucn1_prod_cons_maes_lotes in 'ucn1_prod_cons_maes_lotes.pas' {fcn1_prod_cons_maes_lotes},
  ucn1_prod_cons_maestro in 'ucn1_prod_cons_maestro.pas' {cn1_prod_cons_maestro},
  un1_prod_orde_avan_general in 'un1_prod_orde_avan_general.pas' {fn1_prod_orde_avan_general},
  un1_prod_orde_trazar in 'un1_prod_orde_trazar.pas' {fn1_prod_orde_trazar},
  un1_prod_orde_soli_mate_prima in 'un1_prod_orde_soli_mate_prima.pas' {fn1_prod_orde_soli_mate_prima},
  un2_come_pedi_plan_asignar in 'un2_come_pedi_plan_asignar.pas' {fn2_come_pedi_plan_asignar},
  ufra_info_refe_basico in 'ufra_info_refe_basico.pas' {ffra_info_refe_basico: TFrame},
  ufra_come_sele_pedido in 'ufra_come_sele_pedido.pas' {ffra_come_sele_pedido: TFrame},
  un1_come_pedi_expl_detallada in 'un1_come_pedi_expl_detallada.pas' {fn1_come_pedi_expl_detallada},
  un1_come_expl_padre in 'un1_come_expl_padre.pas' {fn1_come_expl_padre},
  un1_come_pedi_expl_agru_mate_orde_compra in 'un1_come_pedi_expl_agru_mate_orde_compra.pas' {fn1_come_pedi_expl_agru_mate_orde_compra},
  un1_come_pedi_expl_agru_material in 'un1_come_pedi_expl_agru_material.pas' {fn1_come_pedi_expl_agru_material},
  ucn1_prod_cons_pedidos in 'ucn1_prod_cons_pedidos.pas' {fcn1_prod_cons_pedidos},
  un1_cont_nove_diar_costura in 'un1_cont_nove_diar_costura.pas' {fn1_cont_nove_diar_costura},
  un1_prod_orde_extender in 'un1_prod_orde_extender.pas' {fn1_prod_orde_extender},
  un1_prod_orde_corte in 'un1_prod_orde_corte.pas' {fn1_prod_orde_corte},
  un1_prod_orde_liqu_corte in 'un1_prod_orde_liqu_corte.pas' {fn1_prod_orde_liqu_corte},
  urn1_come_pedido in 'urn1_come_pedido.pas' {rn1_come_pedido},
  ufra_prod_espi_totales in 'ufra_prod_espi_totales.pas' {ffra_prod_espi_totales: TFrame},
  ufra_prod_orde_tota in 'ufra_prod_orde_tota.pas' {ffra_prod_orde_tota: TFrame},
  urn1_prod_orde_trazo in 'urn1_prod_orde_trazo.pas' {rn1_prod_orde_trazo},
  urn1_prod_orde_traz_liqu_unidades in 'urn1_prod_orde_traz_liqu_unidades.pas' {rn1_prod_orde_traz_liqu_unidades},
  urn1_prod_orde_Traz_espigas in 'urn1_prod_orde_Traz_espigas.pas' {rn1_prod_orde_Traz_espigas},
  un1_prod_orde_dist_paquetes in 'un1_prod_orde_dist_paquetes.pas' {fn1_prod_orde_dist_paquetes},
  un1_prod_orde_dist_paqu_automatico in 'un1_prod_orde_dist_paqu_automatico.pas' {fn1_prod_orde_dist_paqu_automatico},
  uwn1_prod_fabr_impr_tiquetes in 'uwn1_prod_fabr_impr_tiquetes.pas' {fwn1_prod_fabr_impr_tiquetes},
  uQRTiquetes in 'uQRTiquetes.pas' {fQRTiquetes},
  ucn1_prod_orde_tiqu_fabricacion in 'ucn1_prod_orde_tiqu_fabricacion.pas' {fcn1_prod_orde_tiqu_fabricacion},
  ufra_prod_plan_detallada in 'ufra_prod_plan_detallada.pas' {ffra_prod_plan_detallada: TFrame},
  ucn1_prod_cons_prog_linea in 'ucn1_prod_cons_prog_linea.pas' {cn1_prod_cons_prog_linea},
  un1_meto_esta_buscar in 'un1_meto_esta_buscar.pas' {fn1_meto_esta_buscar},
  un1_plan_depe_procesos in 'un1_plan_depe_procesos.pas' {fn1_plan_depe_procesos},
  un1_form_pago_parametrizacion in 'un1_form_pago_parametrizacion.pas' {fn1_form_pago_parametrizacion},
  un1_form_pago_para_maestro in 'un1_form_pago_para_maestro.pas' {fn1_form_pago_para_maestro},
  un1_form_pago_valo_hora_produccion in 'un1_form_pago_valo_hora_produccion.pas' {fn1_form_pago_valo_hora_produccion},
  un1_form_pago_valo_hora_prod_movil in 'un1_form_pago_valo_hora_prod_movil.pas' {fn1_form_pago_valo_hora_prod_movil},
  un1_form_pago_valo_hora_habilidad1 in 'un1_form_pago_valo_hora_habilidad1.pas' {fn1_form_pago_valo_hora_habilidad1},
  un1_form_pago_valo_hora_habilidad in 'un1_form_pago_valo_hora_habilidad.pas' {fn1_form_pago_valo_hora_habilidad},
  un1_form_pago_valo_habilidad in 'un1_form_pago_valo_habilidad.pas' {fn1_form_pago_valo_habilidad},
  ucn1_prod_orde_tiqu_corte in 'ucn1_prod_orde_tiqu_corte.pas' {fcn1_prod_orde_tiqu_corte},
  un1_form_pago_diferencial in 'un1_form_pago_diferencial.pas' {fn1_form_pago_diferencial},
  un1_form_pago_diferencial1 in 'un1_form_pago_diferencial1.pas' {fn1_form_pago_diferencial1},
  un1_form_pago_diferencial2 in 'un1_form_pago_diferencial2.pas' {fn1_form_pago_diferencial2},
  urn1_prod_dist_paquetes in 'urn1_prod_dist_paquetes.pas' {rn1_prod_dist_paquetes},
  un1_cont_nove_gene_tiquete in 'un1_cont_nove_gene_tiquete.pas' {fn1_cont_nove_gene_tiquete},
  ubPersonal in 'ubPersonal.pas' {bPersonal},
  un1_cont_nove_hora_extras in 'un1_cont_nove_hora_extras.pas' {fn1_cont_nove_hora_extras},
  un1_cont_nove_improductivos in 'un1_cont_nove_improductivos.pas' {fn1_cont_nove_improductivos},
  un1_cont_nove_abonados in 'un1_cont_nove_abonados.pas' {fn1_cont_nove_abonados},
  ucn1_prod_avan_tiquetes in 'ucn1_prod_avan_tiquetes.pas' {cn1_prod_avan_tiquetes},
  ucn1_cont_nove_diarias in 'ucn1_cont_nove_diarias.pas' {cn1_cont_nove_diarias},
  un1_form_pago_dividido in 'un1_form_pago_dividido.pas' {fn1_form_pago_dividido},
  un1_form_pago_dividido1 in 'un1_form_pago_dividido1.pas' {fn1_form_pago_dividido1},
  un1_form_pago_personal in 'un1_form_pago_personal.pas' {fn1_form_pago_personal},
  un1_form_pago_personal1 in 'un1_form_pago_personal1.pas' {fn1_form_pago_personal1},
  un1_form_pago_mixto in 'un1_form_pago_mixto.pas' {fn1_form_pago_mixto},
  ucn1_cont_nove_pago_grupal in 'ucn1_cont_nove_pago_grupal.pas' {cn1_cont_nove_pago_grupal},
  ucn1_cont_nove_pago_grup_sin_ubicacion in 'ucn1_cont_nove_pago_grup_sin_ubicacion.pas' {cn1_cont_nove_pago_grup_sin_ubicacion},
  un1_cali_defectos in 'un1_cali_defectos.pas' {fn1_cali_defectos},
  un1_cali_defectos1 in 'un1_cali_defectos1.pas' {fn1_cali_defectos1},
  un1_cont_nove_defectos in 'un1_cont_nove_defectos.pas' {fn1_cont_nove_defectos},
  ucn1_cont_nove_defe_orde_produccion in 'ucn1_cont_nove_defe_orde_produccion.pas' {fcn1_cont_nove_defe_orde_produccion},
  un1_meto_comp_grupos1 in 'un1_meto_comp_grupos1.pas' {fn1_meto_comp_grupos1},
  un1_meto_comp_variaciones1 in 'un1_meto_comp_variaciones1.pas' {fn1_meto_comp_variaciones1},
  urn1_refe_list_mate_largo in 'urn1_refe_list_mate_largo.pas' {rn1_refe_list_mate_largo},
  un1_prod_orde_soli_inusmos in 'un1_prod_orde_soli_inusmos.pas' {fn1_prod_orde_soli_inusmos},
  un1_come_pedi_expl_agrupada in 'un1_come_pedi_expl_agrupada.pas' {fn1_come_pedi_expl_agrupada},
  uwn1_come_filt_pedidos in 'uwn1_come_filt_pedidos.pas' {fwn1_come_filt_pedidos},
  ufra_sele_rang_fechas in 'ufra_sele_rang_fechas.pas' {ffra_sele_rang_fechas: TFrame},
  ufra_filt_avanzado in 'ufra_filt_avanzado.pas' {ffra_filt_avanzado: TFrame},
  ufra_filt_avan_varios in 'ufra_filt_avan_varios.pas' {ffra_filt_avan_varios: TFrame},
  un1_prod_padr_child in 'un1_prod_padr_child.pas' {fn1_prod_padr_child},
  un1_plan_orde_expl_materiales in 'un1_plan_orde_expl_materiales.pas' {fn1_plan_orde_expl_materiales},
  un1_come_pedi_expl_vari_pedidos in 'un1_come_pedi_expl_vari_pedidos.pas' {fn1_come_pedi_expl_vari_pedidos},
  un1_come_pedi_expl_vari_pedi_agru_supb_material in 'un1_come_pedi_expl_vari_pedi_agru_supb_material.pas' {fn1_come_pedi_expl_vari_pedi_agru_subp_material},
  un1_come_pedi_expl_vari_pedi_agru_material in 'un1_come_pedi_expl_vari_pedi_agru_material.pas' {fn1_come_pedi_expl_vari_pedi_agru_material},
  ufra_edit_reportes in 'ufra_edit_reportes.pas' {ffra_edit_reportes: TFrame},
  ufra_disenar in 'ufra_disenar.pas' {ffra_disenar: TFrame},
  un1_pers_dise_carne1 in 'un1_pers_dise_carne1.pas' {fn1_pers_dise_carne1},
  un0_edit_repo_propiedades in 'un0_edit_repo_propiedades.pas' {fn0_edit_repo_propiedades},
  un1_pers_dise_carne in 'un1_pers_dise_carne.pas' {fn1_pers_dise_carne},
  un0_dial_sele_campos in 'un0_dial_sele_campos.pas' {fn0_dial_sele_campos},
  un0_dial_strings in 'un0_dial_strings.pas' {fn0_dial_strings},
  un1_pers_impr_carne in 'un1_pers_impr_carne.pas' {fn1_pers_impr_carne},
  un1_form_pago_curv_aprendizaje in 'un1_form_pago_curv_aprendizaje.pas' {fn1_form_pago_curv_aprendizaje},
  un1_form_pago_curv_aprendizaje1 in 'un1_form_pago_curv_aprendizaje1.pas' {fn1_form_pago_curv_aprendizaje1},
  un0_conf_cons_lista in 'un0_conf_cons_lista.pas' {fn0_conf_cons_lista},
  un0_conf_editor in 'un0_conf_editor.pas' {fn0_conf_editor},
  un0_wiza_fuen_datos in 'un0_wiza_fuen_datos.pas' {fwiza_fuen_datos},
  un0_dise_consultas in 'un0_dise_consultas.pas' {fn0_dise_consultas},
  uInformesRL in 'uInformesRL.pas' {fInformesRL},
  un0_edit_repo_tipo_banda in 'un0_edit_repo_tipo_banda.pas' {fn0_edit_repo_Tipo_banda},
  ufra_edit_repo_band_color in 'ufra_edit_repo_band_color.pas' {ffra_edit_repo_band_color: TFrame},
  ufra_edit_Repo_band_bordes in 'ufra_edit_Repo_band_bordes.pas' {ffra_edit_Repo_band_bordes: TFrame},
  ufra_edit_repo_fuente in 'ufra_edit_repo_fuente.pas' {ffra_edit_repo_fuente: TFrame},
  ufra_edit_repo_margenes in 'ufra_edit_repo_margenes.pas' {ffra_edit_repo_margenes: TFrame},
  un1_prod_dise_tiquetes1 in 'un1_prod_dise_tiquetes1.pas' {fn1_prod_dise_tiquetes1},
  un0_dial_abrir in 'un0_dial_abrir.pas' {fn0_dial_abrir},
  un0_dise_child in 'un0_dise_child.pas' {fn0_dise_child},
  ufra_edit_SQL in 'ufra_edit_SQL.pas' {ffra_edit_sql: TFrame},
  un0_edit_campos in 'un0_edit_campos.pas' {fn0_edit_campos},
  un0_edit_sql in 'un0_edit_sql.pas' {fn0_edit_sql},
  _uData in '_uData.pas' {_fData: TDataModule},
  ufra_edit_parametrosSQL in 'ufra_edit_parametrosSQL.pas' {ffra_edit_parametrosSQL: TFrame},
  ufra_edit_campos in 'ufra_edit_campos.pas' {ffra_edit_campos: TFrame},
  un0_dise_dial_guar_como in 'un0_dise_dial_guar_como.pas' {fn0_dise_dial_guar_como},
  ufra_arbo_menu in 'ufra_arbo_menu.pas' {ffra_arbo_menu: TFrame},
  un1_meto_tiem_cicl_maquina in 'un1_meto_tiem_cicl_maquina.pas' {fn1_meto_tiem_cicl_maquina},
  un1_meto_tiem_cicl_maquina1 in 'un1_meto_tiem_cicl_maquina1.pas' {fn1_meto_tiem_cicl_maquina1},
  un1_form_pago_bonos in 'un1_form_pago_bonos.pas' {fn1_form_pago_bonos},
  un1_form_pago_bonos1 in 'un1_form_pago_bonos1.pas' {fn1_form_pago_bonos1},
  un1_pers_sistema in 'un1_pers_sistema.pas' {fn1_pers_sistema},
  un1_refe_cata_imagenes in 'un1_refe_cata_imagenes.pas' {fn1_refe_cata_imagenes},
  un1_refe_cata_imagenes1 in 'un1_refe_cata_imagenes1.pas' {fn1_refe_cata_imagenes1},
  un1_refe_fich_maestro in 'un1_refe_fich_maestro.pas' {fn1_refe_fich_maestro},
  un1_refe_fich_sele_tipo in 'un1_refe_fich_sele_tipo.pas' {fn1_refe_fich_sele_tipo},
  un1_refe_fich_00child in 'un1_refe_fich_00child.pas' {fn1_refe_fich_00child},
  un1_refe_fich_maestro1 in 'un1_refe_fich_maestro1.pas' {fn1_refe_fich_maestro1},
  un1_refe_fich_funciones in 'un1_refe_fich_funciones.pas',
  _informesPCP in '_informesPCP.pas' {_fInformesPCP},
  urn1_refe_fich_tecn_base in 'urn1_refe_fich_tecn_base.pas' {rn1_refe_fich_tecn_base},
  urn1_refe_fich_tecn_01_hoja_dise_caratula in 'urn1_refe_fich_tecn_01_hoja_dise_caratula.pas' {rn1_refe_fich_tecn_01_hoja_dise_caratula},
  urn1_refe_fich_tecn_02_hoja_diseno in 'urn1_refe_fich_tecn_02_hoja_diseno.pas' {rn1_refe_fich_tecn_02_hoja_diseno},
  un1_refe_00_maestro in 'un1_refe_00_maestro.pas' {fn1_refe_00_maestro},
  un1_refe_fich_maestro_vista in 'un1_refe_fich_maestro_vista.pas' {fn1_refe_fich_maestro_vista},
  un1_refe_fich_administrador in 'un1_refe_fich_administrador.pas' {fn1_refe_fich_administrador},
  un1_refe_fich_00Edicion in 'un1_refe_fich_00Edicion.pas' {fn1_refe_fich_00Edicion},
  un1_refe_fich_edic_01_hoja_diseno in 'un1_refe_fich_edic_01_hoja_diseno.pas' {fn1_refe_fich_edic_01_hoja_diseno},
  un1_refe_fich_edic_02_hoja_diseno in 'un1_refe_fich_edic_02_hoja_diseno.pas' {fn1_refe_fich_edic_02_hoja_diseno},
  urn1_refe_fich_tecn_03_espe_gene_diseno in 'urn1_refe_fich_tecn_03_espe_gene_diseno.pas' {rn1_refe_fich_tecn_03_espe_gene_diseno},
  un1_refe_Fich_edic_03_espe_gene_diseno in 'un1_refe_Fich_edic_03_espe_gene_diseno.pas' {fn1_refe_Fich_edic_03_espe_gene_diseno},
  un1_refe_fich_edic_04_espe_dise_generales in 'un1_refe_fich_edic_04_espe_dise_generales.pas' {fn1_refe_fich_edic_04_espe_dise_generales},
  urn1_refe_fich_tecn_04_espe_dise_detalles in 'urn1_refe_fich_tecn_04_espe_dise_detalles.pas' {rn1_refe_fich_tecn_04_espe_dise_detalles},
  un1_refe_fich_edic_05_espe_empaque in 'un1_refe_fich_edic_05_espe_empaque.pas' {fn1_refe_fich_edic_05_espe_empaque},
  urn1_refe_fich_tecn_05_espe_empaque in 'urn1_refe_fich_tecn_05_espe_empaque.pas' {rn1_refe_fich_tecn_05_espe_empaque},
  un1_refe_fich_edic_07_medi_especiales in 'un1_refe_fich_edic_07_medi_especiales.pas' {fn1_refe_fich_edic_07_medi_especiales},
  urn1_refe_fich_tecn_07_medi_especiales in 'urn1_refe_fich_tecn_07_medi_especiales.pas' {rn1_refe_fich_tecn_07_medi_especiales},
  un1_refe_fich_edic_06_espe_construccion in 'un1_refe_fich_edic_06_espe_construccion.pas' {fn1_refe_fich_edic_06_espe_construccion},
  un1_refe_fich_edic_06_editor in 'un1_refe_fich_edic_06_editor.pas' {fn1_refe_fich_edic_06_editor},
  urn1_refe_fich_tecn_06_espe_construccion in 'urn1_refe_fich_tecn_06_espe_construccion.pas' {rn1_refe_fich_tecn_06_espe_construccion},
  un1_refe_fich_edic_09_espe_presentacion in 'un1_refe_fich_edic_09_espe_presentacion.pas' {fn1_refe_fich_edic_09_espe_presentacion},
  un1_refe_fich_edic_09_editor in 'un1_refe_fich_edic_09_editor.pas' {fn1_refe_fich_edic_09_editor},
  urn1_refe_fich_tecn_09_espe_presentacion in 'urn1_refe_fich_tecn_09_espe_presentacion.pas' {rn1_refe_fich_tecn_09_espe_presentacion},
  un1_refe_fich_edic_08_medi_pren_terminada in 'un1_refe_fich_edic_08_medi_pren_terminada.pas' {fn1_refe_fich_edic_08_medi_pren_terminada},
  urn1_refe_fich_tecn_08_medi_prenda_1 in 'urn1_refe_fich_tecn_08_medi_prenda_1.pas' {rn1_refe_fich_tecn_08_medi_prenda_1},
  urn1_refe_fich_tecn_08_medi_prenda_2 in 'urn1_refe_fich_tecn_08_medi_prenda_2.pas' {rn1_refe_fich_tecn_08_medi_prenda_2},
  un1_refe_fich_00Seleccion in 'un1_refe_fich_00Seleccion.pas' {fn1_refe_fich_00Seleccion},
  un1_meto_comp_variaciones in 'un1_meto_comp_variaciones.pas' {fn1_meto_comp_variaciones},
  un1_meto_comp_grupos in 'un1_meto_comp_grupos.pas' {fn1_meto_comp_grupos},
  un2_prot_fich_maestro_vista in 'un2_prot_fich_maestro_vista.pas' {fn2_prot_fich_maestro_vista},
  un1_para_sub_Improductivos_Edit in 'un1_para_sub_Improductivos_Edit.pas' {fun1_para_sub_Improductivos_Edit},
  un1_pers_form_pago in 'un1_pers_form_pago.pas' {fn1_pers_form_pago},
  un1_pers_form_pago1 in 'un1_pers_form_pago1.pas' {fn1_pers_form_pago1},
  un1_cont_hora_extr_rangos in 'un1_cont_hora_extr_rangos.pas' {fn1_cont_hora_extr_rangos},
  un1_pers_form_pago_bonos in 'un1_pers_form_pago_bonos.pas' {fn1_pers_form_pago_bonos},
  un1_pers_form_pago_bonos1 in 'un1_pers_form_pago_bonos1.pas' {fn1_pers_form_pago_bonos1},
  ucn1_cont_nove_pago_bruto in 'ucn1_cont_nove_pago_bruto.pas' {cn1_cont_nove_pago_bruto},
  urn1_cont_nove_pago_bruto in 'urn1_cont_nove_pago_bruto.pas' {rn1_cont_nove_pago_bruto},
  ucn1_cont_nove_efic_diario in 'ucn1_cont_nove_efic_diario.pas' {cn1_cont_nove_efic_diario},
  urn1_cont_nove_efic_personal in 'urn1_cont_nove_efic_personal.pas' {rn1_cont_nove_efic_personal},
  un1_cont_prod_curv_apre_operario in 'un1_cont_prod_curv_apre_operario.pas' {fn1_cont_prod_curv_apre_operario},
  un1_meto_comp_list_operaciones in 'un1_meto_comp_list_operaciones.pas' {fn1_meto_comp_list_operaciones},
  _vent_consulta in '_vent_consulta.pas' {_fvent_consulta},
  ucn1_cont_nove_efic_grupo in 'ucn1_cont_nove_efic_grupo.pas' {cn1_cont_nove_efic_grupo},
  ucn1_prod_unid_producidas in 'ucn1_prod_unid_producidas.pas' {cn1_prod_unid_producidas},
  ucn1_cont_prod_quie_reporta in 'ucn1_cont_prod_quie_reporta.pas' {cn1_cont_prod_quie_reporta},
  un0_dial_sele_comb_dataset in 'un0_dial_sele_comb_dataset.pas' {fn0_dial_sele_comb_dataset},
  ufra_edit_repo_alin_texto in 'ufra_edit_repo_alin_texto.pas' {ffra_edit_repo_alin_texto: TFrame},
  ufra_edit_repo_distribucion in 'ufra_edit_repo_distribucion.pas' {ffra_edit_repo_distribucion: TFrame},
  ufra_edit_Repo_imagen in 'ufra_edit_Repo_imagen.pas' {ffra_edit_Repo_imagen: TFrame},
  ufra_edit_sino in 'ufra_edit_sino.pas' {ffra_edit_sino: TFrame},
  ufra_edit_repo_system in 'ufra_edit_repo_system.pas' {ffra_edit_repo_system: TFrame},
  un0_edit_repo_labels in 'un0_edit_repo_labels.pas',
  ufra_edit_repo_codi_Barras in 'ufra_edit_repo_codi_Barras.pas' {ffra_edit_repo_codi_Barras: TFrame},
  ufra_edit_repo_dbResult in 'ufra_edit_repo_dbResult.pas' {ffra_edit_repo_dbResult: TFrame},
  un0_edit_repo_imagenes in 'un0_edit_repo_imagenes.pas' {fn0_edit_repo_imagenes},
  urn1_prod_base_informe in 'urn1_prod_base_informe.pas' {rn1_prod_base_informe},
  urn1_prod_dist_paquetes1 in 'urn1_prod_dist_paquetes1.pas' {rn1_prod_dist_paquetes1},
  un1_prod_lanz_orde_sin_pedido in 'un1_prod_lanz_orde_sin_pedido.pas' {fn1_prod_lanz_orde_sin_pedido},
  un1_prod_orde_dist_paqu_imprimir in 'un1_prod_orde_dist_paqu_imprimir.pas' {fn1_prod_orde_dist_paqu_imprimir},
  un1_prod_dise_tiquetes in 'un1_prod_dise_tiquetes.pas' {fn1_prod_dise_tiquetes},
  un1_cont_prod_cons_indi_eficiencias in 'un1_cont_prod_cons_indi_eficiencias.pas' {fn1_cont_prod_cons_indi_eficiencias},
  UFCN1_Pers_Estados in 'Gustavo\UFCN1_Pers_Estados.pas' {FCN1_Pers_Estados},
  UFRN1_Pers_Estados in 'Gustavo\UFRN1_Pers_Estados.pas' {FRN1_Pers_Estados},
  UFCN1_Pers_Por_Antiguedad in 'Gustavo\UFCN1_Pers_Por_Antiguedad.pas' {FCN1_Pers_Por_Antiguedad},
  UFRN1_Pers_Por_Antiguedad in 'Gustavo\UFRN1_Pers_Por_Antiguedad.pas' {FRN1_Pers_Por_Antiguedad},
  UFCN1_Pers_Por_Cargos in 'Gustavo\UFCN1_Pers_Por_Cargos.pas' {FCN1_Pers_Por_Cargos},
  UFRN1_Pers_Por_Cargos in 'Gustavo\UFRN1_Pers_Por_Cargos.pas' {FRN1_Pers_Por_Cargos},
  UFCN1_Pers_Por_Turnos in 'Gustavo\UFCN1_Pers_Por_Turnos.pas' {FCN1_Pers_Por_Turnos},
  UFRN1_Pers_Por_Turnos in 'Gustavo\UFRN1_Pers_Por_Turnos.pas' {FRN1_Pers_Por_Turnos},
  UFCN1_Pers_Por_Nive_Salarial in 'Gustavo\UFCN1_Pers_Por_Nive_Salarial.pas' {FCN1_Pers_Por_Nive_Salarial},
  UFRN1_Pers_Por_Nive_Salarial in 'Gustavo\UFRN1_Pers_Por_Nive_Salarial.pas' {FRN1_Pers_Por_Nive_Salarial},
  UFCN1_Recu_Ingresos in 'Gustavo\UFCN1_Recu_Ingresos.pas' {FCN1_Recu_Ingresos},
  UFRN1_Recu_Ingresos in 'Gustavo\UFRN1_Recu_Ingresos.pas' {FRN1_Recu_Ingresos},
  UFRN1_Recu_Bajas in 'Gustavo\UFRN1_Recu_Bajas.pas' {FRN1_Recu_Bajas},
  UFCN1_Recu_Bajas in 'Gustavo\UFCN1_Recu_Bajas.pas' {FCN1_Recu_Bajas},
  UFCN1_Recu_Antiguedad in 'Gustavo\UFCN1_Recu_Antiguedad.pas' {FCN1_Recu_Antiguedad},
  UFRN1_Recu_Antiguedad in 'Gustavo\UFRN1_Recu_Antiguedad.pas' {FRN1_Recu_Antiguedad},
  UFCN1_Recu_Traslados in 'Gustavo\UFCN1_Recu_Traslados.pas' {FCN1_Recu_Traslados},
  UFRN1_Recu_Traslados in 'Gustavo\UFRN1_Recu_Traslados.pas' {FRN1_Recu_Traslados},
  UFCN1_Acce_Ingresos in 'Gustavo\UFCN1_Acce_Ingresos.pas' {FCN1_Acce_Ingresos},
  UFRN1_Acce_Ingresos in 'Gustavo\UFRN1_Acce_Ingresos.pas' {FRN1_Acce_Ingresos},
  UFN1_Acce_Ingr_Recursos1 in 'Gustavo\UFN1_Acce_Ingr_Recursos1.pas' {FN1_Acce_Ingr_Recursos1},
  UFCN1_Acce_Bajas in 'Gustavo\UFCN1_Acce_Bajas.pas' {FCN1_Acce_Bajas},
  UFRN1_Acce_Bajas in 'Gustavo\UFRN1_Acce_Bajas.pas' {FRN1_Acce_Bajas},
  UFCN1_Acce_Antiguedad in 'Gustavo\UFCN1_Acce_Antiguedad.pas' {FCN1_Acce_Antiguedad},
  UFRN1_Acce_Antiguedad in 'Gustavo\UFRN1_Acce_Antiguedad.pas' {FRN1_Acce_Antiguedad},
  UFCN1_Acce_Traslados in 'Gustavo\UFCN1_Acce_Traslados.pas' {FCN1_Acce_Traslados},
  UFRN1_Acce_Traslados in 'Gustavo\UFRN1_Acce_Traslados.pas' {FRN1_Acce_Traslados},
  UFN0_Registrar in 'UFN0_Registrar.pas' {FN0_Registrar},
  Un1_meto_oper_cost_tipos1 in 'Un1_meto_oper_cost_tipos1.pas' {fn1_meto_oper_cost_tipos1},
  un1_meto_oper_cost_tipos in 'un1_meto_oper_cost_tipos.pas' {fn1_meto_oper_cost_tipos},
  UN1_Pers_Polifuncionalidad1 in 'UN1_Pers_Polifuncionalidad1.pas' {FN1_Pers_Polifuncionalidad1},
  UN1_Pers_Poli_Maquinas1 in 'UN1_Pers_Poli_Maquinas1.pas' {FN1_Pers_Poli_Maquinas1},
  UN1_Pers_Poli_Operaciones1 in 'UN1_Pers_Poli_Operaciones1.pas' {FN1_Pers_Poli_Operaciones1},
  ucn1_prod_dist_paquetes in 'ucn1_prod_dist_paquetes.pas' {cn1_prod_dist_paquetes},
  uDecisionCube in 'uDecisionCube.pas' {fDecisionCube},
  UFN1_Impr_Tiquetes in 'UFN1_Impr_Tiquetes.pas' {FN1_Impr_Tiquetes},
  ufra_come_desp_a in 'ufra_come_desp_a.pas' {ffra_come_desp_a: TFrame},
  ufra_prod_lotes in 'ufra_prod_lotes.pas' {ffra_prod_lotes: TFrame},
  ufra_edit_parametros in 'ufra_edit_parametros.pas' {ffra_edit_parametros: TFrame},
  UFra_Ficha_Recurso in 'UFra_Ficha_Recurso.pas' {FFra_Ficha_Recurso: TFrame},
  ufra_list_rapida in 'ufra_list_rapida.pas' {ffra_list_rapida: TFrame},
  ufra_mens_atencion2 in 'ufra_mens_atencion2.pas' {ffra_mens_atencion2: TFrame},
  ufra_prod_cort_tota in 'ufra_prod_cort_tota.pas' {ffra_prod_cort_tota: TFrame},
  ufra_prod_lanz_of in 'ufra_prod_lanz_of.pas' {ffra_prod_lanz_of: TFrame},
  ufra_prod_liqu_corte in 'ufra_prod_liqu_corte.pas' {ffra_prod_liqu_corte: TFrame},
  ufra_prod_orde_avance in 'ufra_prod_orde_avance.pas' {ffra_prod_orde_avance: TFrame},
  ufra_prod_orde_bala_proceso in 'ufra_prod_orde_bala_proceso.pas' {ffra_prod_orde_bala_proceso: TFrame},
  ufra_prod_orde_balanceo in 'ufra_prod_orde_balanceo.pas' {ffra_prod_orde_balanceo: TFrame},
  ufra_prod_orde_responsables in 'ufra_prod_orde_responsables.pas' {ffra_prod_orde_responsables: TFrame},
  ufra_prod_orde_tiqu_fabricacion in 'ufra_prod_orde_tiqu_fabricacion.pas' {ffra_prod_orde_tiqu_fabricacion: TFrame},
  ufra_prod_tota_corte in 'ufra_prod_tota_corte.pas' {ffra_prod_corte_tota: TFrame},
  ufra_prod_tota_trazo in 'ufra_prod_tota_trazo.pas' {ffra_prod_tota_trazo: TFrame},
  uin1_para_mone_trm in 'uin1_para_mone_trm.pas' {_fvent_child1},
  un0_accesos in 'un0_accesos.pas' {_fvent_modal1},
  un0_filtros in 'un0_filtros.pas' {fn0_filtros},
  un0_list_rapida in 'un0_list_rapida.pas' {fn0_list_rapida},
  un0_usua_grupos in 'un0_usua_grupos.pas' {fn0_usua_grupos},
  un0_fake in 'un0_fake.pas' {fn0_Fake},
  un1_dise_child in 'un1_dise_child.pas' {fn1_dise_child},
  un1_form_pago_parametrizacion1 in 'un1_form_pago_parametrizacion1.pas' {fn1_form_pago_parametrizacion1},
  un1_form_pago_parametrizacion2 in 'un1_form_pago_parametrizacion2.pas' {fn1_form_pago_parametrizacion2},
  un1_form_pago_pers_bonos in 'un1_form_pago_pers_bonos.pas' {fn1_form_pago_pers_bonos},
  un1_maqu_movi_registro in 'un1_maqu_movi_registro.pas' {fn1_maqu_movi_registro},
  un1_insu_grupos in 'un1_insu_grupos.pas' {fn1_insu_grupos},
  un1_insu_grupos1 in 'un1_insu_grupos1.pas' {fn1_insu_grupos1},
  un1_insu_referencias in 'un1_insu_referencias.pas' {fn1_insu_referencias},
  un1_insu_referencias1 in 'un1_insu_referencias1.pas' {fn1_insu_referencias1},
  un1_insu_subgrupos in 'un1_insu_subgrupos.pas' {fn1_insu_subgrupos},
  un1_insu_subgrupos1 in 'un1_insu_subgrupos1.pas' {fn1_insu_subgrupos1},
  UN1_Maes_Anulados in 'UN1_Maes_Anulados.pas' {FN1_Maes_Anulados},
  un1_maqu_bajas in 'un1_maqu_bajas.pas' {fn1_maqu_bajas},
  un1_maqu_cons_rela_bajas in 'un1_maqu_cons_rela_bajas.pas' {fn1_maqu_cons_rela_bajas},
  un1_maqu_cons_rela_ingr_inventario in 'un1_maqu_cons_rela_ingr_inventario.pas' {fn1_maqu_cons_rela_ingr_inventario},
  un1_mate_grupos in 'un1_mate_grupos.pas' {fn1_mate_grupos},
  un1_mate_grupos1 in 'un1_mate_grupos1.pas' {fn1_mate_grupos1},
  un1_mate_referencias in 'un1_mate_referencias.pas' {fn1_mate_referencias},
  un1_mate_referencias1 in 'un1_mate_referencias1.pas' {fn1_mate_referencias1},
  un1_mate_subgrupos in 'un1_mate_subgrupos.pas' {fn1_mate_subgrupos},
  un1_mate_subgrupos1 in 'un1_mate_subgrupos1.pas' {fn1_mate_subgrupos1},
  un1_mate_unid_medida in 'un1_mate_unid_medida.pas' {fn1_mate_unid_medida},
  un1_mate_unid_medida1 in 'un1_mate_unid_medida1.pas' {fn1_mate_unid_medida1},
  un1_maqu_reingresos in 'un1_maqu_reingresos.pas',
  un1_meto_elem_cst_importar in 'un1_meto_elem_cst_importar.pas' {fn1_meto_elem_cst_importar},
  un1_meto_list_oper_corte in 'un1_meto_list_oper_corte.pas' {fn1_meto_list_oper_corte},
  UN1_Para_Peri_Pago in 'UN1_Para_Peri_Pago.pas' {FN1_Para_Peri_Pago},
  UN1_Para_Peri_Pago1 in 'UN1_Para_Peri_Pago1.pas' {FN1_Para_Peri_Pago1},
  UN1_Para_Plan_Lineas in 'UN1_Para_Plan_Lineas.pas' {FN1_Para_Plan_Lineas},
  UN1_Pers_Bajas1 in 'UN1_Pers_Bajas1.pas' {FN1_Pers_Bajas1},
  UN1_Pers_Confidencial in 'UN1_Pers_Confidencial.pas' {FN1_Pers_Confidencial},
  UN1_Pers_Confidencial1 in 'UN1_Pers_Confidencial1.pas' {FN1_Pers_Confidencial1},
  UN1_Pers_Confidenciales in 'UN1_Pers_Confidenciales.pas' {FN1_Pers_Confidenciales},
  un1_pers_cons_venc_contrato in 'un1_pers_cons_venc_contrato.pas' {fn1_pers_cons_venc_contrato},
  UN1_Pers_Familiar in 'UN1_Pers_Familiar.pas' {FN1_Pers_Familiar},
  UN1_Pers_Familiar1 in 'UN1_Pers_Familiar1.pas' {FN1_Pers_Familiar1},
  un1_pers_hist_movimientos in 'un1_pers_hist_movimientos.pas' {fn1_pers_hist_movimientos},
  UN1_Pers_Historial in 'UN1_Pers_Historial.pas' {FN1_Pers_Historial},
  UN1_Pers_Historial1 in 'UN1_Pers_Historial1.pas' {FN1_Pers_Historial1},
  un1_plan_line_especialidades in 'un1_plan_line_especialidades.pas' {fn1_plan_line_especialidades},
  un1_pers_ingreso_3 in 'un1_pers_ingreso_3.pas' {fn1_pers_ingreso_3},
  UN1_Pers_Movimientos in 'UN1_Pers_Movimientos.pas' {FN1_Pers_Movimientos},
  UN1_Pers_Movimientos1 in 'UN1_Pers_Movimientos1.pas' {FN1_Pers_Movimientos1},
  UN1_Pers_Personal1 in 'UN1_Pers_Personal1.pas' {FN1_Pers_Personal1},
  UN1_Pers_Prestaciones in 'UN1_Pers_Prestaciones.pas' {FN1_Pers_Prestaciones},
  UN1_Pers_Traslados in 'UN1_Pers_Traslados.pas' {FN1_Pers_Traslados},
  UN1_Pers_Traslados1 in 'UN1_Pers_Traslados1.pas' {FN1_Pers_Traslados1},
  un1_plan_secc_procesos in 'un1_plan_secc_procesos.pas' {fn1_plan_secc_procesos},
  un1_prod_asistente in 'un1_prod_asistente.pas' {fn1_prod_asistente},
  un1_prod_avan_general in 'un1_prod_avan_general.pas' {fn1_prod_avan_general},
  un1_prod_cons_gene_fechas in 'un1_prod_cons_gene_fechas.pas' {fn1_prod_cons_gene_fechas},
  UN1_Refe_Costura1 in 'UN1_Refe_Costura1.pas' {FN1_Refe_Costura1},
  un1_prod_paqu_tipos in 'un1_prod_paqu_tipos.pas' {fn1_prod_paqu_tipos},
  un1_prod_proc_paqu_tipos in 'un1_prod_proc_paqu_tipos.pas' {fn1_prod_proc_paqu_tipos},
  un1_prod_proc_paqu_tipos1 in 'un1_prod_proc_paqu_tipos1.pas' {fn1_prod_proc_paqu_tipos1},
  un1_refe_fich_edic_05_espe_em in 'un1_refe_fich_edic_05_espe_em.pas' {fn1_refe_fich_00Edicion1},
  UN1_Refe_Diseno1 in 'UN1_Refe_Diseno1.pas' {FN1_Refe_Diseno1},
  UN1_Refe_Pren_Terminada in 'UN1_Refe_Pren_Terminada.pas' {FN1_Refe_Pren_Terminada},
  UN1_Refe_Pren_Terminada1 in 'UN1_Refe_Pren_Terminada1.pas' {FN1_Refe_Pren_Terminada1},
  UN1_Refe_Presentacion in 'UN1_Refe_Presentacion.pas' {FN1_Refe_Presentacion},
  UN1_Refe_Presentacion1 in 'UN1_Refe_Presentacion1.pas' {FN1_Refe_Presentacion1},
  un1_refe_tipo_variaciones in 'un1_refe_tipo_variaciones.pas' {fn1_refe_tipo_variaciones},
  un1_refe_tipo_variaciones1 in 'un1_refe_tipo_variaciones1.pas' {fn1_refe_tipo_variaciones1},
  un2_come_pedi_cons_por_proveedor in 'un2_come_pedi_cons_por_proveedor.pas' {fn2_come_pedi_cons_por_proveedor},
  un2_come_pedi_expl_materiales in 'un2_come_pedi_expl_materiales.pas' {fn2_come_pedi_expl_materiales},
  un2_cont_cons_lote_unid_fecha in 'un2_cont_cons_lote_unid_fecha.pas' {fn2_cont_cons_lote_unid_fecha},
  un2_pers_matr_poli_nuev_operacion in 'un2_pers_matr_poli_nuev_operacion.pas' {fn2_pers_matr_poli_nuev_operacion},
  un2_pers_matr_polifuncionalidad in 'un2_pers_matr_polifuncionalidad.pas' {fn2_pers_matr_polifuncionalidad},
  un2_prod_orde_estados in 'un2_prod_orde_estados.pas' {fn2_prod_orde_estados},
  un2_prod_orde_etapas in 'un2_prod_orde_etapas.pas' {fn2_prod_orde_etapas},
  un2_prod_orde_etapas1 in 'un2_prod_orde_etapas1.pas' {fn2_prod_orde_etapas1},
  URN1_Refe_Costura1 in 'URN1_Refe_Costura1.pas' {RN1_Refe_Costura1},
  URN1_Refe_Diseno1 in 'URN1_Refe_Diseno1.pas' {RN1_Refe_Diseno1},
  urn1_refe_fich_tecn_07_espe_empaque in 'urn1_refe_fich_tecn_07_espe_empaque.pas' {rn1_refe_fich_tecn_07_espe_empaque},
  URN1_Refe_Presentacion1 in 'URN1_Refe_Presentacion1.pas' {RN1_Refe_Presentacion1},
  misproc2 in 'misproc2.pas',
  un1_referenciasb in 'un1_referenciasb.pas' {fn1_referencias1},
  n0_cont_entrada in 'n0_cont_entrada.pas' {fn0_cont_entrada};

{$R *.RES}
{R RECURS32.RES}

begin
  Application.Initialize;
  //Inicializar las variables del sistema
  TwoDigitYearCenturyWindow := 50;
  DecimalSeparator := '.';
  ThousandSeparator := ',';
  CurrencyString := '$';

  CurrencyFormat := 0;
  NegCurrFormat := 2;
  CurrencyDecimals := 2;
//  ShortTimeFormat := 'hh:mm';
//  LongTimeFormat := 'hh:mm tt';
//  TimeAMString :='A.M.';
//  TimePMString :='P.M.';
//  TimeSeparator := ':';

  Application.CreateForm(T_fMDI, _fMDI);
  Application.CreateForm(T_fData, _fData);
//  Application.CreateForm(Tfn0_conf_editor, fn0_conf_editor);
  Application.Run;
end.
